name: energyscope

dependencies:
  - python >= 3.7
  - numpy >= 1.10
  - matplotlib >= 1.5.1
  - pandas >= 0.19
  - csv
  - json
  - os
  - shutil
  - pathlib
  - logging
  - git
  - datetime
  - amplpy
  - setuptools_scm
